name: Lawnville
favicon: null
layout_spectrum: 0.24601
typography_spectrum: 0.51533
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8fcff'
    - '#012420'
    - '#7c8a78'
    - '#c6695a'
    - '#adc963'
  brandStrength: 0.9527317688334733
  lightness: 0.4677099962718785
  saturation: 0.4955550755839795
  rhythmicContrast: 0.21385029843077064
purpose: []
